# Minni Default Settings

debug: true
port: 3000
host: 0.0.0.0
name: Minni

demo: false

session:
  key: minni-session-id
  secret: MinniIsTrullyAnAwesomeCollaborativeChatToolWithALotOfFeatures

couchdb:
  name: minni-app
  host: 127.0.0.1
  port: 5984

redis:
  host: 127.0.0.1
  port: 6379

auth:
  providers:
    - local
    - minni-github # @minni-im/minni-auth-github
  github:
    scope: user
    callback: /auth/github/callback

login_backgrounds:
  - /images/login/her.jpg
  - /images/login/bokeh.jpg
  - /images/login/tags.jpg

embed:
  disabled: []
