version: '2'
services:
  db:
    image: couchdb:latest
    restart: always
    ports:
      # exposing the port to access fauxton
      - 5984:5984
    volumes:
      - ./logs/couchdb:/usr/local/var/log/couchdb
      - ./etc/couchdb:/usr/local/var/lib/couchdb

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./etc/redis:/data

  minni:
    image: node:latest
    restart: unless-stopped
    links:
      - db:couchdb
      - cache:redis
    volumes:
      - .:/usr/local/var/www
    command: node /usr/local/var/www/index.js
    environment:
      - DOCKER=true

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    links:
      - minni
    volumes:
      - .:/usr/local/var/www
      - ./logs/nginx:/var/log/nginx
      - ./etc/docker.nginx.conf:/etc/nginx/nginx.conf
      - ./etc/docker-nginx.conf.d:/etc/nginx/conf.d
