version: "3"
services:
  db:
    image: couchdb:1.6.1
    restart: always
    ports:
      # exposing the port to access fauxton
      - 5984:5984
    volumes:
      # - ./etc/couchdb:/opt/couchdb/data # 2.3.1
      - ./etc/couchdb:/usr/local/var/lib/couchdb

  cache:
    image: redis:latest
    restart: always
    volumes:
      - ./etc/redis:/data

  minni:
    image: node:latest
    restart: unless-stopped
    depends_on:
      - db
      - cache
    links:
      - "db:couchdb"
      - "cache:redis"
    volumes:
      - .:/usr/local/var/www
    command: node /usr/local/var/www/dist/lib/
    environment:
      - DOCKER=true
      # - MINNI_NAME=Minni Demo
      # - MINNI_DEMO=true
      # - MINNI_SESSION_KEY=minni-demo-session-id
      # - MINNI_COUCHDB_NAME=minni-demo
      # - MINNI_LOGIN_BACKGROUNDS=/images/login/blueprint.jpg,

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    depends_on:
      - minni
    links:
      - "minni"
    volumes:
      - .:/usr/local/var/www
      - ./logs/nginx:/var/log/nginx
      - ./etc/docker.nginx.conf:/etc/nginx/nginx.conf
      - ./etc/docker-nginx.conf.d:/etc/nginx/conf.d
