# Minni Settings File

session:
  key: minni-session-id
  secret: MinniIsTrullyAnAwesomeCollaborativeChatToolWithALotOfFeatures

couchdb:
  name: minni
  host: 127.0.0.1
  port: 5984

auth:
  github:
    #id: your client id here
    #secret: your client secret here
    scope: user
    callback: /auth/github/callback

embed:
  active: true
  providers:
    - Audio
    - Video
    - CodePen
    - Instagram
    - Vimeo
    - Medium
    - Github
    - Gist
    - Flickr
    - Twitter
    - Youtube
    - Spotify
    - Vine
