Vagrant.configure("2") do |config|

  OSX = (/darwin/ =~ RUBY_PLATFORM) != nil

  config.vm.hostname = "minni-app-host"
  config.vm.synced_folder "..", "/vagrant"
  config.vm.box =  "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.name = "minni-app"
    v.memory = 1024
    v.cpus = 2
  end

  # CouchDB forwarding for inspecting w/ futon via http://localhost:5984/_utils
  config.vm.network "forwarded_port", guest: 5984, host: 5984
  # Uncomment to foward Redis port on the guest
  # config.vm.network "forwarded_port", guest: 6379, host: 6379

  if OSX
    # Needed for OSX that does not allow to bind ports < 1024 without root access
    # You then need to configure local firewall to redirect to 80
    # /etc/pf.anchors/com.vagrant
    # rdr pass on lo0 inet proto tcp from any to 127.0.0.1 port 80 -> 127.0.0.1 port 8080
    # https://gist.github.com/f1sherman/843f85ea8e2cbcdb40af
    config.vm.network "forwarded_port", guest: 8080, host: 8080
  else
    config.vm.network "forwarded_port", guest: 8080, host: 80
  end

  # Simply install the latest docker version
  config.vm.provision "docker"

end
